name: paths-ignore-example
on:
  push:
    paths-ignore:
      - 'docs/**'
jobs:
  hello:
    runs-on: ubuntu-20.04
    steps:
    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make
    - name: Run hello
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: hello
