name: structiagram
on:
  workflow_dispatch

jobs:
  generate_diagram:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/install@v0.1
        with:
          crate: structiagram
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: scripts/structiagram.sh git-push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
