name: paths-ignore-example
on:
  push:
    paths-ignore:
      - 'docs/**'
jobs:
  hello:
    runs-on: ubuntu-20.04
    steps:
      - uses: davidB/rust-cargo-make@v1
      - name: Run hello
        run: cargo make hello
